services:
  postgres:
    image: postgres:17-alpine
    user: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:1.39.0
    restart: unless-stopped
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:${DB_PASSWORD}@postgres:5432/logto_db
      - PRIVATE_KEY_ROTATION_GRACE_PERIOD
      - ENDPOINT=https://auth.board.fbridge.pro
      - ADMIN_ENDPOINT=https://admin.board.fbridge.pro
    extra_hosts:
      - "auth.board.fbridge.pro:host-gateway"
      - "admin.board.fbridge.pro:host-gateway"
    networks:
      - app-network

  django:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_NAME=django_db
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=api.board.fbridge.pro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  react:
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - react
      - django
      - logto
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
