# Generated by Django 6.1 on 2026-09-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='allowed_sections',
            field=models.JSONField(blank=True, default=list, help_text='Учитывается только если выключен полный доступ.', verbose_name='Доступные разделы'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='full_access',
            field=models.BooleanField(default=True, help_text='Видит все разделы админки. Если выключено — только разделы ниже.', verbose_name='Полный доступ'),
        ),
    ]
