# Generated by Django 6.0.5 on 2026-06-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logto_organization_id', models.CharField(max_length=255, unique=True, verbose_name='Организация (Logto ID)')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('percent_client', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Процент клиента (%)')),
                ('percent_sebes', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Процент себестоимости (%)')),
                ('swift_client', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='SWIFT клиента')),
                ('swift_sebes', models.DecimalField(decimal_places=2, default=80.0, max_digits=10, verbose_name='SWIFT себестоимости')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organizations',
            },
        ),
    ]
