# Generated by Django 6.0.5 on 2026-06-17 09:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('swift_code', models.CharField(max_length=11, verbose_name='SWIFT')),
                ('bank_type', models.CharField(choices=[('mono', 'Моновалютный'), ('multi', 'Мультивалютный')], default='mono', max_length=5, verbose_name='Тип')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, verbose_name='Номер счёта')),
                ('currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), verbose_name='Валюты')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organizations.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'db_table': 'counterparties',
            },
        ),
        migrations.AddField(
            model_name='bank',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='organizations.counterparty', verbose_name='Контрагент'),
        ),
    ]
