# Generated by Django 6.0.6 on 2026-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_bank_bankaccount_counterparty_bank_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='calculator',
            field=models.CharField(choices=[('standard', 'Стандартный (клиентский)'), ('sebes', 'Себестоимость'), ('no_swift', 'Без SWIFT-комиссии')], default='standard', max_length=50, verbose_name='Калькулятор'),
        ),
    ]
