# Generated by Django 6.0.6 on 2026-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_update_calculator_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='calculator',
            field=models.CharField(choices=[('calc_1', 'Калькулятор 1'), ('calc_2', 'Калькулятор 2')], default='calc_1', max_length=50, verbose_name='Калькулятор'),
        ),
    ]
