# Generated by Django 6.0.6 on 2026-06-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_add_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Плательщик',
                'verbose_name_plural': 'Плательщики',
                'db_table': 'payers',
                'ordering': ['name'],
            },
        ),
    ]
