# Generated by Django 6.0.7 on 2026-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_recipient_initial_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='percent_sebes',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='swift_sebes',
        ),
        migrations.AlterField(
            model_name='organization',
            name='calculator',
            field=models.CharField(choices=[('calc_1', 'Прямой'), ('calc_2', 'Обратный')], default='calc_1', max_length=50, verbose_name='Калькулятор'),
        ),
    ]
