# Generated by Django 6.0.5 on 2026-06-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('usd', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD')),
                ('eur', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс EUR')),
                ('cny', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс CNY')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'db_table': 'exchange_rates',
                'ordering': ['-date'],
            },
        ),
    ]
