# Generated by Django 6.0.5 on 2026-06-17 10:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_bank_bankaccount_counterparty_bank_counterparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_name', models.CharField(max_length=255, verbose_name='Название контрагента')),
                ('counterparty_address', models.CharField(max_length=500, verbose_name='Адрес контрагента')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_address', models.CharField(max_length=500, verbose_name='Адрес банка')),
                ('bank_swift_code', models.CharField(max_length=11, verbose_name='SWIFT')),
                ('bank_account', models.CharField(max_length=50, verbose_name='Номер счёта')),
                ('bank_account_currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), verbose_name='Валюты счёта')),
                ('invoice', models.CharField(max_length=255, verbose_name='Инвойс')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('details', models.TextField(verbose_name='Детали платежа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('new', 'Новая'), ('in_review', 'На проверке'), ('sent_to_bank', 'Отправлена в банк'), ('awaiting_gtd', 'Ожидание ГТД'), ('gtd_review', 'Проверка ГТД'), ('closed', 'Закрыта'), ('correction', 'Исправление')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('prf_organization', models.CharField(blank=True, max_length=255, verbose_name='Организация в РФ')),
                ('prf_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('prf_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма в руб.')),
                ('prf_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('prf_recipient', models.CharField(blank=True, max_length=255, verbose_name='Получатель')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('execution_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс')),
                ('execution_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Затраты')),
                ('execution_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Остаток')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='organizations.bank', verbose_name='Банк')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='organizations.counterparty', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
