# Generated by Django 6.0.6 on 2026-06-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_request_prf_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='execution_costs_sebes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Затраты себестоимости'),
        ),
        migrations.AddField(
            model_name='request',
            name='execution_profit_sebes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='request',
            name='show_paper_download',
            field=models.BooleanField(default=False, verbose_name='Показать ордер на заявку'),
        ),
    ]
