# Generated by Django 6.0.6 on 2026-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_add_sebes_execution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='execution_date_sebes',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения (себест.)'),
        ),
        migrations.AddField(
            model_name='request',
            name='execution_rate_sebes',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс (себест.)'),
        ),
    ]
