# Generated by Django 6.0.6 on 2026-06-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_request_assigned_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='prf_received',
        ),
    ]
