# Generated by Django 6.0.6 on 2026-06-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_remove_prf_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('new', 'Новая'), ('in_review', 'На проверке'), ('sent_to_bank', 'Отправлена в банк'), ('awaiting_gtd', 'Ожидание закрывающих документов'), ('gtd_review', 'Проверка закрывающих документов'), ('closed', 'Закрыта'), ('correction', 'Исправление')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
