# Generated by Django 6.0.6 on 2026-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('new', 'Новая'), ('in_review', 'На проверке'), ('sent_to_bank', 'Отправлена в банк'), ('awaiting_closing_docs', 'Ожидание закрывающих документов'), ('closing_docs_review', 'Проверка закрывающих документов'), ('closed', 'Закрыта'), ('correction', 'Исправление')], default='draft', max_length=30, verbose_name='Статус'),
        ),
    ]
