# Generated by Django 6.0.6 on 2026-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_rename_gtd_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_note',
            field=models.TextField(blank=True, default='', verbose_name='Заметка администратора'),
        ),
    ]
