# Generated by Django 6.0.6 on 2026-07-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_request_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='edit_closing_docs',
            field=models.BooleanField(default=False, verbose_name='Разрешено редактировать закрывающие документы'),
        ),
        migrations.AddField(
            model_name='request',
            name='edit_documents',
            field=models.BooleanField(default=False, verbose_name='Разрешено редактировать документы'),
        ),
        migrations.AddField(
            model_name='request',
            name='edit_payment',
            field=models.BooleanField(default=False, verbose_name='Разрешено редактировать платёж'),
        ),
        migrations.AddField(
            model_name='request',
            name='edit_prf',
            field=models.BooleanField(default=False, verbose_name='Разрешено редактировать плательщика в РФ'),
        ),
    ]
