# Generated by Django 6.0.6 on 2026-07-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_request_edit_closing_docs_request_edit_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('new', 'Новая'), ('in_review', 'На проверке'), ('sent_to_bank', 'Отправлена в банк'), ('awaiting_closing_docs', 'Ожидание закрывающих документов'), ('closing_docs_review', 'Проверка закрывающих документов'), ('closed', 'Закрыта'), ('correction', 'Исправление'), ('correction_review', 'Проверка исправлений')], default='draft', max_length=30, verbose_name='Статус'),
        ),
    ]
