# Generated by Django 6.0.6 on 2026-07-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='money_received',
            field=models.BooleanField(default=False, verbose_name='Деньги пришли'),
        ),
        migrations.AddField(
            model_name='request',
            name='money_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления денег'),
        ),
    ]
