# Generated by Django 6.0.6 on 2026-07-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_request_money_received_request_money_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='money_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отметки о поступлении денег'),
        ),
    ]
