# Generated by Django 6.0.7 on 2026-07-16 09:25

import requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_alter_request_money_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='paper_document',
            field=models.FileField(blank=True, null=True, upload_to=requests.models.paper_document_path, verbose_name='Ордер на заявку'),
        ),
        migrations.AddField(
            model_name='request',
            name='swift_document',
            field=models.FileField(blank=True, null=True, upload_to=requests.models.swift_document_path, verbose_name='SWIFT документ'),
        ),
    ]
