# Generated by Django 6.0.7 on 2026-07-16 09:42

import django.db.models.deletion
import requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0019_request_paper_document_request_swift_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('payment', 'Документы'), ('closing', 'Закрывающие документы')], max_length=10, verbose_name='Блок')),
                ('file', models.FileField(upload_to=requests.models.document_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('size', models.PositiveIntegerField(verbose_name='Размер, байт')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('doc_type', models.CharField(choices=[('invoice', 'Инвойс'), ('request', 'Заявка'), ('gtd', 'ГТД'), ('transport', 'Транспортные'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип документа')),
                ('uploaded_by_admin', models.BooleanField(default=False, verbose_name='Загружено администратором')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requests.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
