# Generated by Django 6.0.7 on 2026-08-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0020_document'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='work_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='schemes.workscheme', verbose_name='Схема работы'),
        ),
    ]
