# Generated by Django 6.0.7 on 2026-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0021_request_work_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sebes_min_fee_applied',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Применён минимум комиссии (Альсафи)'),
        ),
    ]
