# Generated by Django 6.1 on 2026-09-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_request_sebes_min_fee_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sebes_markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Надбавка себестоимости, %'),
        ),
    ]
