# Generated by Django 6.0.7 on 2026-08-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название схемы')),
            ],
            options={
                'verbose_name': 'Схема работы',
                'verbose_name_plural': 'Схемы работы',
                'db_table': 'work_schemes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('CNY', 'CNY')], max_length=3, verbose_name='Валюта')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент (%)')),
                ('swift', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SWIFT')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='schemes.workscheme', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Валюта схемы',
                'verbose_name_plural': 'Валюты схемы',
                'db_table': 'scheme_currencies',
                'ordering': ['scheme', 'currency'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'currency'), name='unique_scheme_currency')],
            },
        ),
    ]
