# Generated by Django 6.0.7 on 2026-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workscheme',
            name='calculator',
            field=models.CharField(choices=[('calc_sebes_mongols', 'Монголы'), ('calc_sebes_ermak', 'Ермак')], default='calc_sebes_mongols', max_length=50, verbose_name='Калькулятор себестоимости'),
        ),
    ]
