# Generated by Django 6.0.7 on 2026-08-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_workscheme_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workscheme',
            name='calculator',
            field=models.CharField(choices=[('calc_sebes_mongols', 'Монголы'), ('calc_sebes_ermak', 'Ермак'), ('calc_sebes_alsafi', 'Альсафи')], default='calc_sebes_mongols', max_length=50, verbose_name='Калькулятор себестоимости'),
        ),
    ]
