# Generated by Django 6.0.6 on 2026-06-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_add_payer'),
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='organizations.payer', verbose_name='Плательщик'),
        ),
    ]
