# Generated by Django 6.0.6 on 2026-06-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_add_payer_to_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='organization',
        ),
    ]
