# Generated by Django 6.0.6 on 2026-07-01 15:25

from decimal import Decimal
from django.db import migrations, models


def backfill_net_amount(apps, schema_editor):
    Receipt = apps.get_model('statement', 'Receipt')
    for receipt in Receipt.objects.filter(net_amount__isnull=True):
        receipt.net_amount = (receipt.amount * Decimal('0.98')).quantize(Decimal('0.01'))
        receipt.save(update_fields=['net_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_remove_organization_from_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма −2%, ₽'),
        ),
        migrations.RunPython(backfill_net_amount, migrations.RunPython.noop),
    ]
