# Generated by Django 6.0.7 on 2026-08-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0006_receipt_m2m_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма −0.2%, ₽'),
        ),
    ]
