# Generated by Django 6.1 on 2026-09-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_remove_organization_percent_sebes_and_more'),
        ('statement', '0007_alter_receipt_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='organizations.payer', verbose_name='Плательщик'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='receipts',
            field=models.ManyToManyField(blank=True, related_name='transfers', to='statement.receipt', verbose_name='Поступления'),
        ),
    ]
