# Generated by Django 6.1 on 2026-09-15 11:28

import django.db.models.deletion
import statement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0008_banktransfer_payer_banktransfer_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=statement.models.transfer_document_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('size', models.PositiveIntegerField(verbose_name='Размер, байт')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='statement.banktransfer', verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Документ перевода',
                'verbose_name_plural': 'Документы переводов',
                'db_table': 'transfer_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
