# Generated by Django 6.1 on 2026-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0009_transferdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('executed', 'Исполнено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
