# Generated by Django 6.0.7 on 2026-08-27 10:22

import django.db.models.deletion
import outgoing_payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=255, verbose_name='Инвойс')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'На исполнении'), ('executed', 'Исполнен')], default='new', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма, ₽')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование поставщика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Исходящий платёж',
                'verbose_name_plural': 'Исходящие платежи',
                'db_table': 'outgoing_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingPaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=outgoing_payments.models.outgoing_payment_document_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('size', models.PositiveIntegerField(verbose_name='Размер, байт')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('outgoing_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='outgoing_payments.outgoingpayment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Документ исходящего платежа',
                'verbose_name_plural': 'Документы исходящих платежей',
                'db_table': 'outgoing_payment_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
