# Generated by Django 6.0.7 on 2026-08-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_remove_organization_percent_sebes_and_more'),
        ('outgoing_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingpayment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_payments', to='organizations.recipient', verbose_name='Счёт списания'),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_progress', 'На исполнении'), ('executed', 'Исполнен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
