# Generated by Django 6.0.7 on 2026-08-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing_payments', '0002_outgoingpayment_account_alter_outgoingpayment_status'),
        ('requests', '0022_request_sebes_min_fee_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingpayment',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='outgoing_payments', to='requests.request', verbose_name='Заявки'),
        ),
    ]
